language: python
python:
- '3.6'
- '3.7'
- '3.8'
install: bash build_tools/travis/install.sh
script: pytest
jobs:
  include:
  - stage: build
    python: '3.7'
    script: echo "Starting Pypi build"
    deploy:
      provider: pypi
      user: __token__
      distributions: sdist bdist_wheel
      password:
        secure: D1TDjxku4krr7SPSuTAjqvM33tlNUqgG1phI7ORPRELno0Fu/KBuvS88uarnc2wTXayEFeTpthQxL+kAnXLOWIKzQhfwmUdVB2ECC+s4TWezbmHgjcMQC4CMQWrTqpQNS6WrI1XP92E8gAkcX9V4ckEPisTdb5KZyIvsO+zUEbbaT4/4PpAJGTODOoy2f0yBTOBMrA8ozyqFDFYG0Q7lacDoB+tK14IpgWp9Snu8Duxlg/e0UAwU8wN5tzB3gtOQnH82r65WfoMYLNlgC0jd+pvHkOADltX7Svgw5dk4Nj3kz8ycgDa/vdsH2BivNfFqmQ38TM0SnPmvUqOpG2EMJG0oVPCr0cMl0TIpRtcZ8eQOrIKRkxe8oF7KdLPu/tOO9jduXh5qlpXTIeXNnmKzM39TdXjahA+31Vc+TB4+eGXv9u5qfpzq4yVQguVgBaEFzBhvRhrDo+JD1DAYa58iZy+pHhkxEqrCVkhs7+hPE1P5xCKcQpjHTl+E/gnqMJdQqJXnPcvTMm6CtauYLB13IDZB9q7XmHbBKOHx9eyy4d4jn2dHiPzOi4xeFxPFAhslyr7MUpY+izCyA7PMtqth7xhs/dpknz4GMufXQNnof8PIjQ/lJnEAbOk3Cr2jbb5JFEJ/P1V/rsCXYzX374RTaztfsgDDeTIXrXH5Kzt3chs=
      on:
        tags: true
        branch: master
